services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-videos_db}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  bot:
    build: .
    depends_on:
      - db
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      POSTGRES_HOST: db
      POSTGRES_PORT: "5432"
      POSTGRES_DB: ${POSTGRES_DB:-videos_db}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      DATA_PATH: ${DATA_PATH:-/data/videos.json}
      FORCE_RELOAD: ${FORCE_RELOAD:-0}

      GIGACHAT_AUTH_KEY: ${GIGACHAT_AUTH_KEY}
      GIGACHAT_SCOPE: ${GIGACHAT_SCOPE:-GIGACHAT_API_PERS}
      GIGACHAT_MODEL: ${GIGACHAT_MODEL:-GigaChat-2-Max}
      GIGACHAT_SSL_VERIFY: ${GIGACHAT_SSL_VERIFY:-0}
    volumes:
      - ./migrations:/migrations:ro
      - ./data:/data:ro
    restart: unless-stopped

volumes:
  pgdata: